### ISSUE TITLE
[Bug]: Internet speed is absolutely horrible

### ISSUE THREAD

**Issue by lopugit** [nullpo-head/wsl-distrod#19]
### Describe the bug

After I installed Distrod, ubuntu focal, I tried installing some programs, but the internet speed is crazy slow.

I had normal WSL 2 installed previously, and the internet speed was fine, just wondering if this issue is well known or?

Kindly

### Steps to reproduce

Install distrod, run a sudo apt-get install command

### Windows version

21H2 19044.1348

### Linux kernel version

Linux win 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Distro

Ubuntu 20.04

### Logs

.

**Comment by nullpo-head** [comment]
Check what's slow is actually the Internet connection or just `apt`, please? Distrod doesn't have any ability to slow down the Internet connection. My guess is you're using the default config of Ubuntu apt that connects to default US servers, and your network location is far from them. Try updating the mirror server list.

**Comment by lopugit** [comment]
I edited my `/etc/apt/sources.list` to use au.archive etc.. url's but it made no different in internet speed. I'm getting speeds of between 1kB/s and 50kB/s, average internet speed to America from Australia is about 400kB/s so, should still be more even if it was from America.

And I ran a speedtest-cli and the output was
```
lopu@win:~$ speedtest
Retrieving speedtest.net configuration...
Testing from iPrimus (218.215.244.93)...
Retrieving speedtest.net server list...
Selecting best server based on ping...
Hosted by Comvergence (Melbourne) [0.42 km]: 20.91 ms
Testing download speed................................................................................
Download: 4.37 Mbit/s
Testing upload speed......................................................................................................
Upload: 21.70 Mbit/s
```

One thing I noticed after installing was that a lot of programs like wget, curl, nano, were not installed already and I had to install them manually, is this normal with Distrod?

**Comment by lopugit** [comment]
I don't think this is a distrod issue. I've tested installing vanilla WSL and it is still doing it. Weird that it only started after using distrod installer but hey. Who knows

**Comment by lopugit** [comment]
this fixed it https://answers.microsoft.com/en-us/windows/forum/all/low-internet-speed-in-wsl-2/21524829-18be-4611-bb5f-cabccd2cae31
