### ISSUE TITLE
[minor] errors on shell startup

### ISSUE THREAD

**Issue by ElDavoo** [nullpo-head/wsl-distrod#2]
Hi,
when I boot up the first shell in Ubuntu Community Preview, I get:
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
grep: /proc/sys/fs/binfmt_misc/WSLInterop: No such file or directory
In the stable Ubuntu, however, I get:
Failed to connect to bus: No such file or directory
Failed to connect to bus: No such file or directory

However, nothing seems to be broken.
 
steps to reproduce: wsl --shutdown and then open up a new shell

**Comment by nullpo-head** [comment]
Thanks for reporting! How did you get "the stable Ubuntu"? From Microsoft Store's "Ubuntu 20.04"?

**Comment by ElDavoo** [comment]
yes

**Comment by nullpo-head** [comment]
Thanks! Can I ask your Windows version, too? Win11 or Win10?

**Comment by rockorequin** [comment]
Is it related to having the package wslu installed? https://askubuntu.com/questions/1318261/nautilus-files-does-not-open-any-of-my-files had the same error message and removing wslu fixed the issue.

**Comment by ElDavoo** [comment]
i don't know, it doesn't happen anymore
