### ISSUE TITLE
[Bug]: Failed to connect to bus: No such file or directory systemctl --user flag

### ISSUE THREAD

**Issue by lopugit** [nullpo-head/wsl-distrod#20]
### Describe the bug

Bug happens when I try to run systemctl with `--user` flag

normal systemctl enable service works fine but I would like to run as user, is this possible?

### Steps to reproduce

systemctl --user enable service

### Windows version

21H2 19044.1348

### Linux kernel version

Linux win 5.10.60.1-microsoft-standard-WSL2 #1 SMP Wed Aug 25 23:20:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Distro

Ubuntu Focal

### Logs

a

**Comment by lopugit** [comment]
Oh does this mean it can't work? https://github.com/nullpo-head/wsl-distrod/issues/13

All good

**Comment by nullpo-head** [comment]
Yes, this issue is a duplicate of #13. As a workaround, do `sudo login -f username` once. user slice will be implemented later.

**Comment by lopugit** [comment]
> Yes, this issue is a duplicate of #13. As a workaround, do `sudo login -f username` once. user slice will be implemented later.

How often do I have to do this though? Just once ever or every session or?
