### ISSUE TITLE
schedule_autostart_task.ps1 regex does not work when PS language is JA

### ISSUE THREAD

**Issue by tomykaira** [nullpo-head/wsl-distrod#4]
```
If ([bool](schtasks /query /fo list | Select-String -pattern "TaskName:\s+\\{{TASK_NAME}}" -quiet)) {
```

This part requires the system language is English, because the regex has `TaskName` literal.
However, when OS language settings is Japanese, the `schtasks` command puts something like this:

```
タスク名:        \StartWSL_Ubuntu_for_desktop-xxxxxx-tomyk
```

How about just removing `TaskName:` because `\s+\\{{TASK_NAME}}` is enough to identify the newly registered task?

**Comment by nullpo-head** [comment]
Thanks for the catch! I'll fix it today later. It also would be very helpful if you could send your local change as a PR.
