### ISSUE TITLE
Change the name of the distro

### ISSUE THREAD

**Issue by machsix** [nullpo-head/wsl-distrod#8]
Is there any way to change the name of the distro created with distrod? https://github.com/microsoft/WSL/issues/4241 mentioned exporting and reimporting. I'm not sure whether it's safe to do so

**Comment by nullpo-head** [comment]
If you're willing to re-install your distro, you can install Distrod with custom name by `-d` option. See [Install and Run Multiple Distros at the same time](https://github.com/nullpo-head/wsl-distrod/blob/main/docs/references.md#install-and-run-multiple-distros-at-the-same-time)

In addition, importing and exporting Distrod itself is as safe as regular WSL2 distros.
